apiVersion: v2
name: thmnayah
description: A Helm chart for Thmnayah Content Management Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mongodb
    version: 13.18.5
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
